using Photon.Pun;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using UnityEngine;

public class PhotonPlayer : MonoBehaviour
{

	private PhotonView PV;
	public GameObject myAvatar;
    // Start is called before the first frame update
    void Start()
    {
		PV = GetComponent<PhotonView>();
		int spawnPicker = Random.Range(0, GameSetupController.GS.spawnPoints.Length);
		if (PV.IsMine)
		{
			myAvatar = PhotonNetwork.Instantiate(Path.Combine("PhotonPrefabs", "PlayerAvatar"), 
				GameSetupController.GS.spawnPoints[spawnPicker].position, GameSetupController.GS.spawnPoints[spawnPicker].rotation, 0);
		}
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
